name: Compile Check
on: push

jobs:
  check-compilation:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository contents
      uses: actions/checkout@v2
    - name: Configure JDK for compilation
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - name: Compile source code
      run: javac *.java
